### ISSUE TITLE
list of requirements

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#1]

**Comment by janaoravcova** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3736577/Katalog.poziadaviek.pdf)

**Comment by SmiesnaA** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/4185003/Katalog.poziadaviek.pdf)
