### ISSUE TITLE
specification of requirements

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#2]
all requirements need to be specified by the assigner

**Comment by janaoravcova** [comment]
All requirements have been specified.

**Comment by janaoravcova** [comment]
Assigner wanted to correct  some parts of document.

**Comment by pavelpetrovic** [comment]
k aktualnej verzii:

- ucel dokumentu: pre koho je urceny, poziadavky na analyzu rizik? podrobnejsie uviest ucel dokumentu
- 2.3.  - k "zakladnym informaciam"  - nie je jasne, co sa tym mysli
- 2.4. offline - prosim upresnit, co sa tym mysli
- 2.5. Javy ako jazyka => asi myslite JRE
- prosim oddelit RD a A-VS1
ostatne ste si zapisali a rozumeli.

**Comment by janaoravcova** [comment]
[katalog-poziadaviek.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3771483/katalog-poziadaviek.pdf)

**Comment by pavelpetrovic** [comment]
Dakujem za aktualizaciu KP. Ide to dobrym smerom. Posielam dalsie komentare na upravy.
Zapracujte ich, prosim, dosledne a POTOM si este kazdy kriticky precitajte cely KP znovu a skontrolujte, ci tam netreba nieco upravit. Ked vsetci potvrdia, ze to maju precitane a uz nevidia nic, co treba upravit, tak potom to uz poslite zadavatelom na validaciu - poproste ich, aby si to cele znova dokladne prestudovali a dali Vam k tomu spatnu vazbu, pripomienky, opravy, doplnenia, lebo podla tohto system budete vyvijat.
Tu su:
- pridajte si prosim pod nadpis aj svoje mena
- 1.1 pre koho je dokument urceny?
- spravu dat o projektoch projektov??
- len pre istotu: toto je stale pravda?
   "datami o FEM simulaciach spravovanymi spravcom FEM-karov vo forme Excel suboru"
-  "do logov v textovych suborov." => koncovka
- pozor aj na pravopis, napr. "s databazov", "nie je obmedzeni", atd.
- "A-VS1 - Aplikacia po uvedeni" => tesne po uvedeni  (inak to nie je pravda, lebo aj rok po uvedeni je "po uvedeni")
- A-VS2 => takyto level som neocakaval, ale ked uz to tam mate, tak to tam nechajme :) treba ale upravit "admina" na "kazdeho pouzivatela s priradenou rolou administratora", lebo inak nie je jasne, ci to plati len pre toho prveho admina, alebo pre kazdeho takeho. co asi nie je pravda, lebo adminom sa stane, az ked mu priradi iny admin tuto rolu a vtedy uz ma nejake svoje heslo, takze po priradeni roly admina si ho musi zmenit? dotiahnite tento bod... (mozete aj tak, ze ho vypustite, pretoze heslo prveho admina moze byt nastavovane najakym instalacnym postupom, ktory moze byt opisany v instalacnej prirucke, zaroven by ten postup mohol fungovat na zmenu hesla admina, ak je to potrebne z dovodu zachrany systemu a pod.)
- A-VS5: 
posle notikaciu => prida notifikaciu
a udelenim prislusnej roly => vypustit (pouzivatel neziada o rolu, iba o registraciu, ziadost o pridelenie roly prebieha mimo system - ustne, mailom a pod. - to netreba uvadzat)
od slova "Notifikacia" to dajte to samostatnej poziadavky
Navrhujem vsak, aby tento typ notifikacie nemal krizik "x", ale iba dva "buttony": potvrdit, zamietnut.
Oba sposobia, ze sa vsetkym pouzivatelom s rolou admina prestane notifikacia zobrazovat. "Zamietnut" sposobi uplne vymazanie prislusneho pouzivatela, "potvrdit" sposobi nastavenie defaultnej roly "pouzivatel". Inu rolu mu moze admin pridelit podla A-VS13.
- A-VS13:  checkboxy alebo radio buttony? Inymi slovami, su roly exkluzivne, alebo moze mat viac ako jednu rolu? (prosim upresnit)
- A-VS7: navrhujem vypustit slovo "vsetkym", znie to ako keby ostatni mohli aspon niektore a registrovani vsetko.
- A-RA3:  vyhovujucim => vyhovujucich
- A-RA5: Offeres (preklep)
- A-RA6: su niektore z tychto udajov importovane z excelu? ak ano, nie je problem, ze sa rucne zmenia? moze menit vsetky udaje, ktore su zobrazene?
- A-RA7: daju stiahnut => daju ulozit do suboru    (nie ste webova app)
grafy => kolko je tych grafov?
co v tych grafoch je? ake su to grafy? (stplcove, kolacove, ciarove,...) co je na x-ovej osi, co na y-ovej osi?
- A-RA7, A-RA8: nie je jasne, ci tieto dve poziadavky hovoria o tych grafoch, alebo nie. upravte formulacie tak, aby to bolo jednoznacne
- A-RA8:  
hodnot => datumov
nie je jasne, ci ma kazdy graf svoj vlastny filter, alebo plati filter pre vsetky grafy
- A-RA9: prosim presne definovat podmienky "hroziaceho rizika"
- A-RFS2: kazdy FEM-kar ma svoju tabulku alebo su vsetci v jednej tabulke? (prosim upresnit) ak je tabulka pre kazdeho zvlast, co presne znamena "zobrazi vsetkych FEM-karov"?
- B-RFS3: toto je asi 5 kombinovanych poziadaviek, ktore by sa patrilo rozdrobit na jednotlivosti.
- B-RFS5:  je pocas editovania dostupne aj tlacidlo +? ak ano, sposobi zrusenie editovania ostatnych buniek? v rezime editovania sa da nejakym inym sposobom pridat riadok?
- B-RFS6: uf, nebolo by lepsie, ak by sa FEM-kar len deaktivoval, aby jeho udaje mohli byt aspon prezeratelne aj neskor, nemali by sa odlozit do nejakej historie??
- A-RFS7: nepodstatne navrhy: mozno by tam mohlo byt aj tlacidlo na vycistenie filtra. tiez by sa mi pacilo, keby tie filtre boli dropboxy, aby nemusel pisat cely kod projektu, cislo dielu, alebo sa pomylit v pismene v mene zakaznika
- A-RFS8: uvodzovky :) aj tu su: A-VS13
- B-RFS9: ak sa tabulky FEM-karov nevojdu do okna, bude sa dat scrollovat?
- A-VS10: ma moznost nieco z toho zmenit?
- A-VS12: to iste, moze robit nejake zmeny okrem roly? ak je pouzivatel adminom pre specificky projekt, je to v zozname zobrazene?
- A-VS13: 3 checkboxy pre kazdu => 3 checkboxy, jeden pre kazdu 
- otazky: moze admin pre specificky projekt robit ostatne veci, co moze admin?
- je nejaky centralny admin iny ako admin s pravami na vsetky projekty?
- A-VS15: asi by to bolo predsa len lepsie dat do databazy, aby to bolo centralne, inak tie zmeny budu rozhadzane per partes na vsetkych pocitacoch cez ktore tam pristupuju - staci jednoducha tabulka s poliami datum, id pouzivatela, popis akcie  a jedno tlacidlo v rozhrani admina, ktorym sa to da vyexportovat do .txt suboru
- chyba mi moznost vyexportovania udajov o FEM simulaciach do csv suboru
zelam vela trpezlivosti a uspechov!

**Comment by blackoctopus21** [comment]
[katalog-poziadaviek.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3775284/katalog-poziadaviek.pdf)

**Comment by pavelpetrovic** [comment]
za mňa super! skvelé! ďakujem!
(ostali tam ešte jedny úvodzovky - text in work aplikacia)
