### ISSUE TITLE
architecture design documentation

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#26]

**Comment by janaoravcova** [comment]
[navrh.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3864043/navrh.pdf)

**Comment by SmiesnaA** [comment]
[Navrh.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3890466/Navrh.pdf)

**Comment by janaoravcova** [comment]
[Navrh.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3893014/Navrh.pdf)

**Comment by blackoctopus21** [comment]
[Navrh.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3964305/Navrh.pdf)

**Comment by SmiesnaA** [comment]
[Návrh.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/4185025/Navrh.pdf)
