### ISSUE TITLE
test scenarious

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#28]
[testovacie scenáre.docx](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3893073/testovacie.scenare.docx)

**Comment by janaoravcova** [comment]
[testovacie scenáre.docx](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3906428/testovacie.scenare.docx)
version 1.1

**Comment by SmiesnaA** [comment]
[Testovacie_scenáre.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/4185009/Testovacie_scenare.pdf)
