### ISSUE TITLE
directory acces permission  - export

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#36]
musime vyriesit kam sa budu ukladat exportovanie subory - bud v nejakom konfiguracnom textovom subore zada pouzivatel zelanu destinaciu, na ktoru ale musi mat pravo, alebo napevno zvolime nejaku po dohode vo firme

**Comment by blackoctopus21** [comment]
Neda sa nejak nastavit ze do pocitaca do downloads ?

**Comment by janaoravcova** [comment]
dá sa nastaviť akákoľvek destinácia, len treba mať oprávnenie do nej písať.
Tak môžem dať downloads :)

**Comment by SmiesnaA** [comment]
Ja by som to dala tiež napevno do Downloads :)
