### ISSUE TITLE
inštalačný manuál - konfigurácia databázy

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#44]

**Comment by SmiesnaA** [comment]
[MySQL návod na konfiguráciu.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/4188929/MySQL.navod.na.konfiguraciu.pdf)

**Comment by pavelpetrovic** [comment]
najskor - do takychto technickych dokumentov prosim nedavajte prazdne titulne listy, to je zbytocne a zabera to miesto.
tento workbench si zbytocne budu instalovat, ked tie tabulky mozu vytvorit priamo na serveri pomocou tej mysql command line utility ako som Vam hovoril. Ale ved co uz narobim.
