### ISSUE TITLE
design basics of user interface

### ISSUE THREAD

**Issue by janaoravcova** [TIS2019-FMFI/project-risk-analysis#5]
Choose color pallete and design of basic components in application.

**Comment by blackoctopus21** [comment]
[Grafické používateľské rozhranie.pdf](https://github.com/TIS2019-FMFI/project-risk-analysis/files/3802272/Graficke.pouzivatelske.rozhranie.pdf)

**Comment by pavelpetrovic** [comment]
ak su s tym uz vsetci stotozneni a povazujete to za finalne, potreboval by som, aby aspon jeden clovek za nimi zasiel na osobne stretnutie a detailne prediskutoval, ako bude aplikacia na tychto obrazkoch fungovat. bolo by to mozne, prosim?
